repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: black
        types: [python]
  
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        language: system
        entry: autoflake
        args: [--expand-star-imports, --remove-all-unused-imports, --remove-unused-variables, --in-place, --recursive, test_project/, django_admin_search_fields/]
        types: [python]

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]